project:
  type: website
  output-dir: docs
  
website:
  back-to-top-navigation: true
  page-footer: 
    left: "製作者：何明信老師2026" 
#    right: 
#      - icon: github
#        href: https://github.com/
#      - icon: twitter 
#        href: https://twitter.com/   
    background: light

  title: "教學網站 - 何明信老師"
  navbar:
    background: primary
    search: true
    left:
      - text: "首頁"
        href: index.qmd
        target: _blank
      - text: 危險性機械及設備管理
        href: https://peter7336959.github.io/HME/
        target: _blank
      - text: 暴露評估
        href: https://peter7336959.github.io/EA/
        target: _blank
      - text: 事故調查制度實務指南
        href: https://www.coapre.org.tw/tw/resources-download-content/f98F8f9006DF
        target: _blank
      - text: 其他(新增中)
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - text: "介紹"
        href: index.qmd
      - section: "甲業"
        contents:
          - text: RA 基本概念
            href: RA_Basic.qmd
            target: _blank                
          - text: HSE RA
            href: HSE職安衛整體風險評估概念.qmd
            target: _blank        
          - text: 甲業安全RA
            href: 甲業＿風險評估詳實版.qmd
            target: _blank            
          - text: 營甲_施工安全RA
            href: 營甲＿施工風險評估.qmd
            target: _blank    
          - text: RA研究導讀
            href: RA研究導讀.qmd
            target: _blank                   
          - text: 職業衛生EA
            href: 職業衛生暴露風險評估與實務.qmd
            target: _blank                          
      - section: "職安衛人員"
        contents:
          - text: 機械設備器具安全與風險評估
            href: 機械設備器具安全與風險評估.qmd
            target: _blank
          - text: 具有危險性之機械及設備安全相關法規簡介
            href: 具有危險性之機械及設備安全相關法規簡介.qmd
            target: _blank 
          - text: 危險性機械及設備管理
            href: 危險性機械及設備管理.qmd
            target: _blank            
      - section: "學校種子人員"
        contents:
          - text: 化學有害物危害預防策略
            href: https://peter7336959.github.io/teaching/%E6%A0%A1%E5%9C%92%EF%BC%BF%E5%8C%96%E5%AD%B8%E6%9C%89%E5%AE%B3%E7%89%A9%E5%8D%B1%E5%AE%B3%E9%A0%90%E9%98%B2%E7%AD%96%E7%95%A5.html
            target: _blank
          - text: 高溫接觸危害預防策略
            href: 校園＿高溫接觸危害預防策略.qmd
            target: _blank
      - section: "書籍簡讀"
        contents:
          - text: 大腦解鎖(Limitless mind)
            href: https://peter7336959.github.io/teaching/books/B_大腦解鎖.html
            target: _blank        
          - text: 反智(The irrational age)
            href: https://peter7336959.github.io/teaching/books/B_反智.html
            target: _blank
          - text: 問題是, 我大概會活很久(Somewhere Towards the End)
            href: https://peter7336959.github.io/teaching/books/B_問題是我大概會活很久.html
            target: _blank           
          - text: 不對稱陷阱(Skin in the game)
            href: reading1.qmd
            target: _blank
      - section: "職衛師"
        contents:
          - text: 局部排氣控制與設計
            href: 局部排氣控制與設計.qmd
            target: _blank            
          - text: 工業毒物學概論
            href: H_工業毒物學概論.qmd
            target: _blank 
          - text: 勞工作業環境監測及暴露評估訓練班
            href: 監測及暴露評估案例實作.qmd
            target: _blank            
          - text: BDA
            href: BDA.qmd
            target: _blank            

format:
  html:
    theme: cosmo
    css: style/style.css
    toc: true